---
title: "Gastrulation:"
output:
  BiocStyle::html_document: 
    toc: false
    fig_width: 10
    fig_height: 8
---

```{r load_modules, echo=FALSE, include=FALSE}
library(data.table)
library(purrr)
library(ggplot2)
library(scater)

matrix.please <- function(x) {
    m<-as.matrix(x[,-1])
    rownames(m)<-x[[1]]
    m
}

theme_pb <- function() {
  theme(
    axis.text.x = element_text(size=rel(1.7), color="black", angle=50, vjust=1, hjust=1),
    axis.text.y = element_text(size=rel(1.2), color="black"),
    axis.title.y = element_text(size=rel(1.4), color="black"),
    strip.background = element_rect(fill="#F37A71"),
    strip.text = element_text(size=rel(2.4), color="black"),
    # strip.text.x = element_text(size=rel(1.45), color="black"),
    legend.position="top",
    legend.title = element_blank()
  )
}
```

<!-- Define I/O and options -->
```{r define_opts, echo=FALSE}

## Define I/O ##
io <- list()
io$sample.metadata <- "/Users/ricard/data/Guo_2017/sample_metadata.txt"
io$met.dir <- "/Users/ricard/data/Guo_2017/met/feature_level"
io$acc.dir <- "/Users/ricard/data/Guo_2017/acc/feature_level"
io$outdir <- "/Users/ricard/Guo_2017/boxplots_enhancers/out"
io$annos_dir <- "/Users/ricard/data/gastrulation/features/filt"
io$gene_metadata <- "/Users/ricard/data/ensembl/mouse/v87/BioMart/mRNA/Mmusculus_genes_BioMart.87.txt"

## Define options ##
opts <- list()

# Define which stage and lineages to look at 
opts$stage <- c(
  # "Zygote"
  "2-cell",
  "4-cell",
  "8-cell",
  "16-cell",
  "Morula",
  "ICM"
  # "ESC",
  # "TE"
)

opts$met.annos <- c(
  # "genebody",
  # "prom_2000_2000_noncgi",
  # "prom_2000_2000_cgi",
  # "prom_2000_2000",
  "H3K27ac_distal_E7.5_Mes_intersect12",
  "H3K27ac_distal_E7.5_Ect_intersect12",
  "H3K27ac_distal_E7.5_End_intersect12"
)

opts$acc.annos <- c(
  # "genebody",
  # "prom_200_200_noncgi",
  # "prom_200_200_cgi",
  # "prom_200_200",
  "H3K27ac_distal_E7.5_Mes_intersect12",
  "H3K27ac_distal_E7.5_Ect_intersect12",
  "H3K27ac_distal_E7.5_End_intersect12"
)

opts$overlapGenes <- FALSE

min.fdr <- 0.1
min.diff <- 0.10

# opts$colors <- c(
#   "E4.5 Epi"="gray80", 
#   "E5.5 Epi"="gray60", 
#   "E6.5 Epi"="grey40", "E6.5 PS"="sandybrown", 
#   "E7.5 Ect"="steelblue", "E7.5 End"="#43CD80", "E7.5 Mes"="violetred"
# )

# Define which cells to use
tmp <- fread(io$sample.metadata)
opts$met_cells <- tmp %>% .[stage%in%opts$stage,id_met]
opts$acc_cells <- tmp %>% .[stage%in%opts$stage,id_acc]
```

<!-- Load sample metadata -->
```{r load_metadata}
sample_metadata <- fread(io$sample.metadata)
```

<!-- Load methylation data -->
```{r load_data, echo=FALSE, include=FALSE}
met_dt <- lapply(opts$met.annos, function(n) {
  data <- fread(cmd=sprintf("zcat < %s/%s.tsv.gz",io$met.dir,n), showProgress=F, stringsAsFactors=T, quote="") %>%
  .[V1%in%opts$met_cells]
}) %>% rbindlist
colnames(met_dt) <- c("id_met","id","anno","Nmet","N","rate")
```

<!-- Load accessibility data -->
```{r load_data, echo=FALSE, include=FALSE}
acc_dt <- lapply(opts$acc.annos, function(n) {
  data <- fread(cmd=sprintf("zcat < %s/%s.tsv.gz",io$acc.dir,n), showProgress=F, stringsAsFactors=T, quote="") %>%
  .[V1%in%opts$acc_cells]
}) %>% rbindlist
colnames(acc_dt) <- c("id_acc","id","anno","Nmet","N","rate")
```

<!-- Load differentially methylated hits -->
```{r}
io$diff.met <- "/Users/ricard/data/gastrulation_norsync_stuff/met/test/diff_featurelevel"

# Mesoderm-specific
diff.met.mes <- lapply(opts$met.annos, function(x)
  fread(cmd=sprintf("zcat < %s/E7.5Mes_vs_E7.5EctEnd_%s.txt.gz",io$diff.met,x))
) %>% rbindlist() 

# Ectoderm-specific
diff.met.ect <- lapply(opts$met.annos, function(x)
  fread(cmd=sprintf("zcat < %s/E7.5Ect_vs_E7.5MesEnd_%s.txt.gz",io$diff.met,x))
) %>% rbindlist()

# Endoderm-specific
diff.met.end <- lapply(opts$met.annos, function(x)
  fread(cmd=sprintf("zcat < %s/E7.5End_vs_E7.5EctMes_%s.txt.gz",io$diff.met,x))
) %>% rbindlist()

# diff.met <- do.call("rbind", list(diff.met.mes,diff.met.end,diff.met.ect)) %>%
#   .[,sig:=padj_fdr<0.01 & abs(diff)>0.10]
```

<!-- Load differentially accessible sites -->
```{r}
io$diff.acc <- "/Users/ricard/data/gastrulation_norsync_stuff/acc/test/diff_featurelevel"

# Mesoderm-specific
diff.acc.mes <- lapply(opts$acc.annos, function(x)
  fread(cmd=sprintf("zcat < %s/E7.5Mes_vs_E7.5EctEnd_%s.txt.gz",io$diff.acc,x))
) %>% rbindlist()

# Ectoderm-specific
diff.acc.ect <- lapply(opts$acc.annos, function(x)
  fread(cmd=sprintf("zcat < %s/E7.5Ect_vs_E7.5MesEnd_%s.txt.gz",io$diff.acc,x))
) %>% rbindlist()

# Endoderm-specific
diff.acc.end <- lapply(opts$acc.annos, function(x)
  fread(cmd=sprintf("zcat < %s/E7.5End_vs_E7.5EctMes_%s.txt.gz",io$diff.acc,x))
) %>% rbindlist()

# diff.acc <- do.call("rbind", list(diff.acc.mes,diff.acc.end,diff.acc.ect)) %>%
#   .[,sig:=padj_fdr<0.01 & abs(diff)>0.15]
```

<!-- Merge data with metadata -->
```{r merge}
acc_dt <- merge(acc_dt, sample_metadata[,c("sample","id_acc","stage")], by="id_acc") %>% droplevels()
met_dt <- merge(met_dt, sample_metadata[,c("sample","id_met","stage")], by="id_met") %>% droplevels()
```

<!-- Subset differential sites from the data -->

Methylation
```{r}
# Mesoderm enhancers
mes <- diff.met.mes %>% .[,sig:=padj_fdr<min.fdr & abs(diff)>min.diff] %>%
  .[sig==T & anno=="H3K27ac_distal_E7.5_Mes_intersect12"]

# Endoderm enhancers
end <- diff.met.end %>% .[,sig:=padj_fdr<min.fdr & abs(diff)>min.diff] %>%
  .[sig==T & anno=="H3K27ac_distal_E7.5_End_intersect12"]

# Ectoderm enhancers
ect <- diff.met.ect %>% .[,sig:=padj_fdr<min.fdr & abs(diff)>min.diff] %>%
  .[sig==T & anno=="H3K27ac_distal_E7.5_Ect_intersect12"]

met.sig.hits <- rbindlist(list(mes,end,ect))

# Subset data
met_dt.sig <- met_dt %>% split(.$anno) %>%
  map2(.,names(.), function(x,y) x[id%in%met.sig.hits[anno==y,id]]) %>%
  rbindlist %>% droplevels()
```

Accessibility
```{r}
# Mesoderm enhancers
mes <- diff.acc.mes %>% .[,sig:=padj_fdr<min.fdr & abs(diff)>min.diff] %>%
  .[sig==T & anno=="H3K27ac_distal_E7.5_Mes_intersect12"]

# Endoderm enhancers
end <- diff.acc.end %>% .[,sig:=padj_fdr<min.fdr & abs(diff)>min.diff] %>%
  .[sig==T & anno=="H3K27ac_distal_E7.5_End_intersect12"]

# Ectoderm enhancers
ect <- diff.acc.ect %>% .[,sig:=padj_fdr<min.fdr & abs(diff)>min.diff] %>%
  .[sig==T & anno=="H3K27ac_distal_E7.5_Ect_intersect12"]

acc.sig.hits <- rbindlist(list(mes,end,ect))

# Subset data
acc_dt.sig <- acc_dt %>% split(.$anno) %>%
  map2(.,names(.), function(x,y) x[id%in%acc.sig.hits[anno==y,id]]) %>%
  rbindlist %>% droplevels()
```


```{r}
met.sig.hits[,.N,by=c("anno")]
acc.sig.hits[,.N,by=c("anno")]
```

<!-- Boxplots with accessibility rate per genomic context and stage -->
```{r}
annos <-c(
  "H3K27ac_distal_E7.5_End_intersect12"="Endoderm enhancers",
  "H3K27ac_distal_E7.5_Mes_intersect12"="Mesoderm enhancers",
  "H3K27ac_distal_E7.5_Ect_intersect12"="Ectoderm enhancers"
)

foo <- acc_dt.sig[anno%in%names(annos)] %>%
  .[,.(rate=sum(Nmet)/sum(N), Nmet=sum(Nmet), N=sum(N), nsites=.N),by=c("sample","stage","anno")] %>%
  .[,rate:=rate*100] %>%
  .[,anno:=stringr::str_replace_all(anno,annos)] %>%
  .[,stage:=factor(stage,levels=opts$stage)] %>%
  droplevels() 

p <- ggplot(foo, aes(x=stage, y=rate)) +
  geom_boxplot(aes(fill=stage), outlier.shape=NA) +
  # scale_fill_manual(values=opts$colors) +
  labs(x="", y="Accessibility rate") +
  facet_wrap(~anno, nrow=1, scales="fixed") +
  coord_cartesian(ylim=c(0,60)) +
  theme_bw() +
  guides(color=F, fill=F) +
  theme_pb() +
  theme(strip.background = element_rect(fill="#00BFC4"))
print(p)

# pdf(paste0(io$outdir,"/boxplots_acc.pdf"), useDingbats = F, onefile = F, width=14, height=6)
# print(p)
# dev.off()
```

<!-- Boxplots with methylation rate per genomic context and stage -->
```{r}
annos <-c(
  "H3K27ac_distal_E7.5_Ect_intersect12"="Ectoderm enhancers",
  "H3K27ac_distal_E7.5_End_intersect12"="Endoderm enhancers",
  "H3K27ac_distal_E7.5_Mes_intersect12"="Mesoderm enhancers"
)

foo <- met_dt.sig[anno%in%names(annos)] %>%
  .[,.(rate=sum(Nmet)/sum(N), Nmet=sum(Nmet), N=sum(N), nsites=.N),by=c("sample","stage","anno")] %>%
  .[,rate:=rate*100] %>%
  .[,anno:=stringr::str_replace_all(anno,annos)] %>%
  .[,stage:=factor(stage,levels=opts$stage)] %>%
  droplevels()  

p <- ggplot(foo, aes(x=stage, y=rate)) +
  geom_boxplot(aes(fill=stage), outlier.shape=NA) +
  # scale_fill_manual(values=opts$colors) +
  labs(x="", y="Methylation rate") +
  facet_wrap(~anno, nrow=1, scales="fixed") +
  coord_cartesian(ylim=c(0,100)) +
  theme_bw() +
  guides(color=F, fill=F) +
  theme_pb() +
  theme(strip.background = element_rect(fill="#F37A71"))
print(p)

# pdf(paste0(io$outdir,"/boxplots_met.pdf"), useDingbats = F, onefile = F, width=14, height=6)
# print(p)
# dev.off()
```

