---
title: "Gastrulation scNMT-seq: pseudobulked profiles of DNA methylation and chromatin accessibility"
output: 
  BiocStyle::html_document: 
    fig_width: 10
    fig_height: 8
---

```{r load_modules, echo=FALSE, include=FALSE}
library(data.table)
library(purrr)
library(ggplot2)
```

<!-- Define I/O and options -->
```{r define_options, echo=FALSE}
if (grepl("ricard",Sys.info()['nodename'])) {
  base <- "/Users/ricard/Guo_2017/metacc/profiles"
} else if (grepl("yoda",Sys.info()['nodename'])) {
  base <- "/homes/ricard/Guo_2017/metacc/profiles"
} else {
  stop("Computer not recognised")
}

source(paste0(base,"/load_settings.R"))

io$outdir <- paste0(io$basedir,"/metacc/profiles")
dir.create(io$outdir, showWarnings = F)
```

<!-- (ONLY FOR TESTING) Subset cells to reduce memory burden -->
```{r}
# opts$ncells <- 3
# opts$filt.cells <- sample_metadata[,head(unique(sample),n=opts$ncells),by="stage"] %>% .$V1
# 
# sample_metadata <- sample_metadata[sample %in% opts$filt.cells]
# opts$met.cells <- sample_metadata$id_met
# opts$acc.cells <- sample_metadata$id_acc
```

<!-- Load genomic annotations -->
```{r load_data, echo=FALSE}
source(paste0(base,"/load_annotations.R"))
```

<!-- Load data -->
This takes a long time, see code chunk later where we load the pre-computed object
```{r load_data, echo=FALSE}
source(paste0(base,"/load_data.R"))
```

<!-- Merge DNA methylation and chromatin acessibility data -->
```{r}
data <- rbind(
  met[,c("sample","stage","id","anno","dist","rate","context")],
  acc[,c("sample","stage","id","anno","dist","rate","context")]
)
data[,rate:=rate*100]
```

<!-- Rename genomic contexts -->
```{r}
# data[,anno:=stringr::str_replace_all(anno,opts$annos)]
```

Load pre-computed object
```{r}
# saveRDS(data, paste0(io$outdir,"/precomputed.rds"))

# data <- readRDS("/Users/ricard/data/gastrulation/metacc/pseudobulked_profiles/lineage_enhancers/data.rds")
```

<!-- Load genome-wide global methylation and accessibility rates -->
```{r}
met.stats <- fread(io$met.stats) %>%
  merge(sample_metadata[,.(sample,id_met)], by="id_met") %>% .[,context:="CG"]

acc.stats <- fread(io$acc.stats) %>%
  merge(sample_metadata[,.(sample,id_acc)], by="id_acc") %>% .[,context:="GC"]

stats <- rbind(
  met.stats[,c("sample","mean","coverage","context")],
  acc.stats[,c("sample","mean","coverage","context")]
) %>% merge(sample_metadata[,c("sample","stage")],by="sample")# %>%
  # .[,.(mean=mean(mean)),by=c("stage","context")]
```


<!-- Plot joint methylation and accessibility profiles -->

Per stage, genomic contexts side by side
```{r}
p_list <- list()

for (i in as.character(unique(data$stage))) {
  print(i)
  
  tmp <- data[stage==i]
  
  p_list[[i]] <- ggplot(tmp, aes(x=dist, y=rate, group=context, fill=context, color=context)) +
    facet_wrap(~anno, nrow=1, scales="fixed") +
    stat_summary(geom="ribbon", fun.data="mean_se", alpha=1) +
    stat_summary(geom="line", fun.data="mean_se") +
    geom_hline(yintercept=stats[context=="CG" & stage==i,median(mean,na.rm=T)], color="#F37A71", linetype="dashed", alpha=0.75, size=0.75) +
    geom_hline(yintercept=stats[context=="GC" & stage==i,median(mean,na.rm=T)], color="#00BFC4", linetype="dashed", alpha=0.75, size=0.75) +
    labs(x="Distance from center (bp)", y="Met/Acc levels (%)") +
    coord_cartesian(ylim=c(0,50)) +
    # scale_x_continuous(breaks=c(-1,0,1)) +
    xlim(-opts$window_size, opts$window_size) +
    guides(fill=FALSE, color=FALSE, linetype=FALSE) +
    theme_classic() +
    theme(
      axis.text.x = element_text(size=rel(0.8), colour="black"),
      axis.text.y = element_text(size=rel(1.2), colour="black")
    )

  pdf(file=sprintf("%s/%s.pdf",io$outdir,i), width=8.5, height=5)
  print(p_list[[i]])
  dev.off()
}
```


Per cell
```{r}
p_list <- list()

for (i in as.character(unique(data$sample))) {
  print(i)
  
  tmp <- data[sample==i]
  
  p_list[[i]] <- ggplot(tmp, aes(x=dist, y=rate, group=context, fill=context, color=context)) +
    facet_wrap(~anno, nrow=1, scales="fixed") +
    stat_summary(geom="ribbon", fun.data="mean_se", alpha=1) +
    stat_summary(geom="line", fun.data="mean_se") +
    geom_hline(yintercept=stats[context=="CG" & sample==i,mean], color="#F37A71", linetype="dashed", alpha=0.75, size=0.75) +
    geom_hline(yintercept=stats[context=="GC" & sample==i,mean], color="#00BFC4", linetype="dashed", alpha=0.75, size=0.75) +
    labs(x="Distance from center (bp)", y="Met/Acc levels (%)") +
    coord_cartesian(ylim=c(0,50)) +
    # scale_x_continuous(breaks=c(-1,0,1)) +
    xlim(-opts$window_size, opts$window_size) +
    guides(fill=FALSE, color=FALSE, linetype=FALSE) +
    theme_classic() +
    theme(
      axis.text.x = element_text(size=rel(0.8), colour="black"),
      axis.text.y = element_text(size=rel(1.2), colour="black")
    )
  # print(p_list[[i]])

  pdf(file=sprintf("%s/per_cell/%s.pdf",io$outdir,i), width=8.5, height=5)
  print(p_list[[i]])
  dev.off()
}
```

```{r}
stop()
```

STOP HERE


```{r}
foo <- data[,.(ratio=mean(.SD[abs(dist)<200,rate])/mean(.SD[abs(dist)>1800,rate])), by=c("sample","context")] %>%
  .[,context:=paste0("ratio_",context)] %>%
  dcast(sample~context, value="ratio")

bar <- foo %>% 
  merge(stats%>%dcast(formula=sample~context, value.var=c("mean","coverage")), by="sample")
```


```{r}
ggscatter(bar, x="ratio_CG", y="ratio_GC", color="mean_CG", shape="pass_metQC") +
  # coord_cartesian(xlim = c(0.01,1.01), ylim=c(0,2)) +
  geom_hline(yintercept=1, linetype="dashed", color="black") +
  geom_vline(xintercept=1, linetype="dashed", color="black") +
  geom_vline(xintercept=0.5, linetype="dashed", color="red") +
  scale_colour_distiller(palette="Reds", direction=1)

fail_metqc <- bar[pass_metQC==T & ratio_CG>0.5 ,sample]
```

```{r}
ggscatter(bar, x="ratio_CG", y="ratio_GC", color="mean_GC", shape="pass_accQC") +
  # coord_cartesian(xlim = c(0.01,1.01), ylim=c(0,2)) +
  geom_hline(yintercept=1, linetype="dashed", color="black") +
  geom_vline(xintercept=1, linetype="dashed", color="black") +
  geom_hline(yintercept=1, linetype="dashed", color="blue") +
  scale_colour_distiller(palette="Blues", direction=1)

fail_accqc <- bar[pass_metQC==T & ratio_GC<1 ,sample]
```

```{r}
table(metadata$pass_metQC)
table(metadata$pass_accQC)
```

```{r}
metadata <- fread(io$metadata)
metadata %>%
  .[sample%in%fail_metqc, pass_metQC:=FALSE] %>%
  .[sample%in%fail_accqc, pass_accQC:=FALSE]
```

```{r}
table(metadata$pass_metQC)
table(metadata$pass_accQC)
```

```{r}
# fwrite(metadata, io$metadata, sep="\t", col.names=T, row.names=F, quote=F, na="NA")
```

