---
title: "Gastrulation: pseudobulked profiles of DNA methylation and chromatin accessibility"
output: 
  BiocStyle::html_document: 
    fig_width: 10
    fig_height: 8
---

```{r load_modules, echo=FALSE, include=FALSE}
library(data.table)
library(purrr)
library(ggplot2)
```

```{r fncs, echo=FALSE}
theme_boxplot <- function() {
    theme(
      plot.margin = unit(c(t=1,r=1,b=1,l=1), "cm"),
      plot.title = element_text(size=25,hjust=0.5),
      axis.text=element_text(size=15, colour="black"),
      axis.title.x=element_text(size=17, margin=margin(10,0,0,0)),
      axis.title.y=element_text(size=17, margin=margin(0,10,0,0)),
      axis.line = element_line(size=rel(1.0)),
      axis.ticks = element_line(size=rel(1.3), color="black"),
      legend.key = element_blank(),
      legend.position = "top",
      legend.direction = "horizontal",
      # legend.key.size= unit(0.5, "cm"),
      legend.key.width=unit(1.2,"line"),
      legend.key.height=unit(1.0,"line"),
      legend.margin = margin(t=10, r=0, b=0, l=0, unit="pt"),
      legend.title = element_blank(),
      legend.text = element_text(size=15),
      panel.border=element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      panel.background=element_blank()
    )
}

f <- function(x) { return(data.frame(y=mean(x), ymin=mean(x)-sd(x), ymax=mean(x)+sd(x))) }
```


```{r define_options, echo=FALSE}

# Define I/O
io <- list()
io$basedir <- "/Users/ricard/data/Guo2017_preimplantation"
io$outdir <- "/Users/ricard/Guo2017_preimplantation/out"
io$in.sample_metadata <- paste0(io$basedir,"/sample_metadata.txt")
io$features.indir <- paste(io$basedir,"features/filt",sep="/")
io$met.indir <- paste(io$basedir,"met/raw/",sep="/")
io$acc.indir <- paste(io$basedir,"acc/raw/",sep="/")
io$diffmet.dir <- "/Users/ricard/data/gastrulation_norsync_stuff/met/test/diff_featurelevel"
io$diffacc.dir <- "/Users/ricard/data/gastrulation_norsync_stuff/acc/test/diff_featurelevel"

# Define options
opts <- list()
opts$window_size <- 2000
opts$met.tile <- 150
opts$acc.tile <- 100

# opts$window_size <- 1500
# opts$met.tile <- 100
# opts$acc.tile <- 50


# Define which annotations to use and where to center the windows
opts$annos <- c(
  "prom_100_100"="center",
  "H3K27ac_distal_E7.5_Ect_intersect12"="center",
  "H3K27ac_distal_E7.5_Mes_intersect12"="center",
  "H3K27ac_distal_E7.5_End_intersect12"="center"
  # "TSC_distal_H3K27ac"="center"
)

# Define annotation names
opts$anno.names <-c(
  "prom_100_100"="Promoters",
  "H3K27ac_distal_E7.5_Ect_intersect12"="Ectoderm enhancers",
  "H3K27ac_distal_E7.5_Mes_intersect12"="Mesoderm enhancers",
  "H3K27ac_distal_E7.5_End_intersect12"="Endoderm enhancers"
  # "TSC_distal_H3K27ac"="Trophoblast enhancers"
)

# Define stages
opts$stage <- c("Zygote", "2-cell", "4-cell", "8-cell", "Morula", "ICM")
# opts$stage <- c("ESC")

# Define which cells to use
sample_metadata <- fread(io$in.sample_metadata,stringsAsFactors=T) %>% 
  .[stage%in%opts$stage] 
  
opts$met.cells <- sample_metadata$id_met %>% as.character
opts$acc.cells <- sample_metadata$id_acc %>% as.character
```

<!-- Load genomic annotations -->
```{r load_annotations, echo=FALSE, warning=FALSE}
anno_list <- list()
for (anno in names(opts$annos)) {
  tmp <- fread(sprintf("%s/%s.bed",io$features.indir,anno))[,c(1,2,3,4,5,6)]
  colnames(tmp) <- c("chr","start","end","strand","id","anno")
  
  # Define central position for the window approach
  if (opts$annos[anno] == "start") {
    tmp <- rbind(tmp[strand=="+",.(chr,start,strand,id,anno)] %>% .[,center:=start] %>% .[,c("start"):=NULL], 
                 tmp[strand=="-",.(chr,end,strand,id,anno)] %>% .[,center:=end] %>% .[,c("end"):=NULL]) 
  }
  if (opts$annos[anno] == "center") {
    stopifnot(all(tmp[,end] > tmp[,start]))
    tmp <- tmp[,.(chr,start,end,strand,id,anno)][,center:=round(end+start)/2][,c("start","end"):=NULL]
  }
  if (opts$annos[anno] == "end") {
    tmp <- rbind(tmp[strand=="+",.(chr,end,strand,id,anno)][,center:=end][,c("end"):=NULL], 
                 tmp[strand=="-",.(chr,start,strand,id,anno)][,center:=start][,c("start"):=NULL])
  }
  anno_list[[anno]] <- tmp %>% .[, c("start","end") := list(center-opts$window_size,center+opts$window_size)]
}

anno_df <- rbindlist(anno_list) %>% 
  .[,c("anno","chr"):=list(as.factor(anno),as.factor(sub("chr","",chr)))] %>%
  setkey(chr,start,end)
rm(anno_list)
```

```{r}
# Mesoderm-specific
diff.met.mes <- fread(cmd=sprintf("zcat < %s/E7.5Mes_vs_E7.5EctEnd_H3K27ac_distal_E7.5_Mes_intersect12_500.txt.gz",io$diffmet.dir))

# Ectoderm-specific
diff.met.ect <- fread(cmd=sprintf("zcat < %s/E7.5Ect_vs_E7.5MesEnd_H3K27ac_distal_E7.5_Ect_intersect12_500.txt.gz",io$diffmet.dir))

# Endoderm-specific
diff.met.end <- fread(cmd=sprintf("zcat < %s/E7.5End_vs_E7.5EctMes_H3K27ac_distal_E7.5_End_intersect12_500.txt.gz",io$diffmet.dir))

# diff.met <- do.call("rbind", list(diff.met.mes,diff.met.end)) %>% .[sig==T]
diff.met <- do.call("rbind", list(diff.met.ect, diff.met.mes, diff.met.end)) %>%
  .[padj_fdr<0.05 & abs(diff)>=0.05] %>%
  .[,c("id","anno"):=list(stringr::str_replace_all(id,"_500",""),stringr::str_replace_all(anno,"_500",""))]
```

```{r}
diff.met[,.N,by="anno"]
```

```{r}
# Mesoderm-specific
diff.acc.mes <- fread(cmd=sprintf("zcat < %s/E7.5Mes_vs_E7.5EctEnd_H3K27ac_distal_E7.5_Mes_intersect12.txt.gz",io$diffacc.dir))

# Ectoderm-specific
diff.acc.ect <- fread(cmd=sprintf("zcat < %s/E7.5Ect_vs_E7.5MesEnd_H3K27ac_distal_E7.5_Ect_intersect12.txt.gz",io$diffacc.dir))

# Endoderm-specific
diff.acc.end <- fread(cmd=sprintf("zcat < %s/E7.5End_vs_E7.5EctMes_H3K27ac_distal_E7.5_End_intersect12.txt.gz",io$diffacc.dir))

# diff.acc <- do.call("rbind", list(diff.acc.mes,diff.acc.end)) %>% .[sig==T]
diff.acc <- do.call("rbind", list(diff.acc.ect, diff.acc.mes, diff.acc.end)) %>% 
  .[padj_fdr<0.05 & abs(diff)>=0.05]
```

```{r}
diff.acc[,.N,by="anno"]
```

<!-- Subset differential hits from the data -->
```{r}
# Methylation
anno_df.met.subset <- anno_df %>% split(.$anno) %>%
  map2(.,names(.), function(x,y) x[id %in% diff.met[anno==y,id]] ) %>%
  rbindlist
# anno_df.met.nonsubset <- anno_df[!anno%in%opts$subset.annnos]
# anno_df.met <- rbind(anno_df.met.subset,anno_df.met.nonsubset) %>% droplevels() %>% setkey(chr,start,end)
anno_df.met <- anno_df.met.subset %>% setkey(chr,start,end)

# Accessibility
anno_df.acc.subset <- anno_df %>% split(.$anno) %>%
  map2(.,names(.), function(x,y) x[id %in% diff.acc[anno==y,id]] ) %>%
  rbindlist
# anno_df.acc.nonsubset <- anno_df[!anno%in%opts$subset.annnos]
# anno_df.acc <- rbind(anno_df.acc.subset,anno_df.acc.nonsubset) %>% droplevels() %>% setkey(chr,start,end)
anno_df.acc <- anno_df.acc.subset %>% setkey(chr,start,end)
```

```{r}
# anno_df.met <- rbind(anno_df.met,anno_df[anno=="prom_100_100"]) %>% setkey(chr,start,end)
# anno_df.acc <- rbind(anno_df.acc,anno_df[anno=="prom_100_100"]) %>% setkey(chr,start,end)
```


<!-- Load methylation data -->
```{r load_data, echo=FALSE}
met_list <- list()
for (cell in opts$met.cells) {
  tmp <- fread(cmd=sprintf("zcat < %s/%s.tsv.gz",io$met.indir,cell), showProgress=F, stringsAsFactors=F) %>%
    setnames(c("chr","pos","rate")) %>% .[,id_met:=cell] %>% 
    .[,c("start","end"):=pos] %>% setkey("chr","start","end") %>%
    
    foverlaps(.,anno_df, nomatch=0) %>% .[, c("chr","i.start","i.end") := NULL] %>%
    .[,id:=as.character(id)] %>%
    .[,dist:=ifelse(strand %in% c("+","*"),pos-center,center-pos)] %>% 
    .[, dist:=opts$met.tile*round(dist/opts$met.tile)] %>%
    .[,list(rate=mean(rate), n=.N),by=.(id_met,id,dist,anno)]
  met_list[[cell]] <- tmp
}
met <- rbindlist(met_list) %>%
  .[,c("id_met","id","context"):=list(as.factor(id_met),as.factor(id),"CG")]
  
# rm(met_list)
```

<!-- Load accessibility data -->
```{r}
acc_list <- list()
for (cell in opts$acc.cells) {
  tmp <- fread(cmd=sprintf("zcat < %s/%s.tsv.gz",io$acc.indir,cell), showProgress=F, stringsAsFactors=F) %>%
    setnames(c("chr","pos","rate")) %>% .[,id_acc:=cell] %>% 
    .[,c("start","end"):=pos] %>% setkey("chr","start","end") %>%
    
    foverlaps(.,anno_df, nomatch=0) %>% .[, c("chr","i.start","i.end") := NULL] %>%
    .[,id:=as.character(id)] %>%
    .[,dist:=ifelse(strand %in% c("+","*"),pos-center,center-pos)] %>% 
    .[, dist:=opts$acc.tile*round(dist/opts$acc.tile)] %>%
    .[,list(rate=mean(rate), n=.N),by=.(id_acc,id,dist,anno)]
  acc_list[[cell]] <- tmp
}
acc <- rbindlist(acc_list) %>%
  .[,c("id_acc","id","context"):=list(as.factor(id_acc),as.factor(id),"GC")]
  
# rm(acc_list)
```

<!-- Merge data with sample metadata -->
```{r}
met <- met %>% merge(sample_metadata[,c("sample","id_met","stage")], by="id_met") %>%
  droplevels()
acc <- acc %>% merge(sample_metadata[,c("sample","id_acc","stage")], by="id_acc") %>%
droplevels()
```

<!-- Combine methylation and accessibility data -->
```{r}
data <- rbind(
  met[,c("sample","stage","id","anno","dist","rate","context")],
  acc[,c("sample","stage","id","anno","dist","rate","context")]
)
```

```{r}
data[,rate:=rate*100]
```

<!-- Summarise across all genome-wide features -->
```{r}
data_filt <- data %>%
  .[,.(rate=mean(rate), N=.N, var=var(rate)), by=c("stage","dist","anno","context")]
# fwrite(data_filt, "/Users/ricard/data/gastrulation_norsync_stuff/foo.txt", quote=F)
```

```{r}
# met.stats <- fread("/Users/ricard/gastrulation/met/stats/samples/out/sample_stats.txt") %>% .[anno=="all",.(id_met,mean)] %>%
#   merge(sample_metadata[,.(sample,id_met)], by="id_met") %>% .[,context:="CG"]
# 
# acc.stats <- fread("/Users/ricard/gastrulation/acc/stats/samples/out/sample_stats.txt") %>% .[anno=="all",.(id_acc,mean)] %>%
#   merge(sample_metadata[,.(sample,id_acc)], by="id_acc") %>% .[,context:="GC"]
# 
# stats <- rbind(met.stats[,c("sample","mean","context")],acc.stats[,c("sample","mean","context")]) %>%
#   merge(sample_metadata[,c("sample","stage")],by="sample") %>%
#   .[,.(mean=mean(mean)),by=c("context")]
```

<!-- Plot joint methylation and accessibility profiles -->

Per stage, genomic contexts side by side
```{r}
for (i in as.character(unique(data$stage))) {
  print(i)
  
  tmp <- data[stage==i] %>%  
    .[,anno:=stringr::str_replace_all(anno,opts$anno.names)]
  
  p <- ggplot(tmp, aes(x=dist, y=rate, group=context, fill=context, color=context)) +
    facet_wrap(~anno, nrow=1, scales="fixed") +
    stat_summary(geom="ribbon", alpha=0.10) +
    stat_summary(geom="line") +
    # geom_hline(yintercept=stats[context=="CG" & stage==i,mean(mean,na.rm=T)], color="#F37A71", linetype="dashed", alpha=0.75, size=0.75) +
    # geom_hline(yintercept=stats[context=="GC" & stage==i,mean(mean,na.rm=T)], color="#00BFC4", linetype="dashed", alpha=0.75, size=0.75) +
    # labs(x="Distance from center (bp)", y="Rate", title=i) +
    labs(title=i, x="", y="") +
    # coord_cartesian(ylim=c(5,55)) +
    xlim(-opts$window_size, opts$window_size) +
    # scale_colour_manual(values=opts$colors) +
    guides(fill=FALSE, color=FALSE, linetype=FALSE) +
    theme_boxplot() +
    theme(
      # axis.text.x = element_text(size=rel(0.9), colour="black"),
      axis.text.x = element_blank(),
      axis.text.y = element_text(size=rel(1.1), colour="black"),
      axis.title.x = element_text(size=rel(1.0), margin=margin(10,0,0,0)),
      axis.title.y = element_text(size=rel(1.0), margin=margin(0,10,0,0)),
      axis.line = element_line(size=rel(1.0)),
      axis.ticks = element_line(size=rel(1.3), color="black"),
      legend.text = element_text(size=11),
      strip.text = element_blank()
    )
  # print(p)

  pdf(file=sprintf("%s/%s.pdf",io$outdir,i), width=8.5, height=5)
  print(p)
  dev.off()
}
```


Per cell, genomic contexts side by side
```{r}
# for (i in as.character(unique(data$stage))) {
#   for (j in as.character(unique(data[stage==i,sample]))) {
#     tmp <- data[stage==i & sample==j] %>% .[,anno:=stringr::str_replace_all(anno,opts$anno.names)]
#     p <- ggplot(tmp, aes(x=dist, y=rate, group=context, fill=context, color=context)) +
#       facet_wrap(~anno, nrow=1, scales="fixed") +
#       
#       # stat_summary(geom="ribbon", alpha=0.10) +
#       # stat_summary(geom="line") +
#       
#       stat_summary(fun.data="mean_se", geom="smooth", size=1.0, data=tmp[context=="GC" & stage==i], color="#00BFC4", fill="#00BFC4", alpha=0.5) +
#       stat_summary(fun.data="mean_se", geom="smooth", size=1.0, data=tmp[context=="CG" & stage==i], color="#F37A71", fill="#F37A71", alpha=0.5) +
#       
#       # labs(x="Distance from center (bp)", y="Rate", title=i) +
#       labs(x="", y="") +
#       coord_cartesian(ylim=c(5,55)) +
#       xlim(-opts$window_size, opts$window_size) +
#       # scale_colour_manual(values=opts$colors) +
#       guides(fill=FALSE, color=FALSE, linetype=FALSE) +
#       theme_boxplot() +
#       theme(
#         # axis.text.x = element_text(size=rel(0.9), colour="black"),
#         axis.text.x = element_blank(),
#         axis.text.y = element_text(size=rel(1.1), colour="black"),
#         axis.title.x = element_text(size=rel(1.0), margin=margin(10,0,0,0)),
#         axis.title.y = element_text(size=rel(1.0), margin=margin(0,10,0,0)),
#         axis.line = element_line(size=rel(1.0)),
#         axis.ticks = element_line(size=rel(1.3), color="black"),
#         legend.text = element_text(size=11),
#         strip.text = element_blank()
#       )
# 
#     pdf(file=sprintf("%s/percell/%s_%s.pdf",io$outdir,i,j), width=8.5, height=5)
#     print(p)
#     dev.off()
#   }
# }
```
