---
title: "Gastrulation:"
output: 
  BiocStyle::html_document: 
    fig_width: 10
    fig_height: 8
---

```{r load_modules, echo=FALSE, include=FALSE}
library(data.table)
library(purrr)
library(ggplot2)
```

```{r fncs, echo=FALSE}
matrix.please<-function(x) {
    m<-as.matrix(x[,-1])
    rownames(m)<-x[[1]]
    m
}

theme_boxplot <- function() {
    theme(
      plot.margin = unit(c(t=1,r=1,b=1,l=1), "cm"),
      plot.title = element_text(size=25,hjust=0.5),
      axis.text=element_text(size=15, colour="black"),
      axis.title.x=element_text(size=17, margin=margin(10,0,0,0)),
      axis.title.y=element_text(size=17, margin=margin(0,10,0,0)),
      axis.line = element_line(size=rel(1.0)),
      axis.ticks = element_line(size=rel(1.3), color="black"),
      legend.key = element_blank(),
      legend.position = "top",
      legend.direction = "horizontal",
      # legend.key.size= unit(0.5, "cm"),
      legend.key.width=unit(1.2,"line"),
      legend.key.height=unit(1.0,"line"),
      legend.margin = margin(t=10, r=0, b=0, l=0, unit="pt"),
      legend.title = element_blank(),
      legend.text = element_text(size=15),
      panel.border=element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      panel.background=element_blank()
    )
}

f <- function(x) { return(data.frame(y=mean(x), ymin=mean(x)-sd(x), ymax=mean(x)+sd(x))) }
```


```{r define_options, echo=FALSE}

# Define I/O
io <- list()
io$basedir <- "/Users/ricard/data/Guo2017_preimplantation"
io$outdir <- "/Users/ricard/test"
io$in.sample_metadata <- paste0(io$basedir,"/sample_metadata.txt")
io$features.indir <- paste(io$basedir,"features/filt",sep="/")
io$met.indir <- paste(io$basedir,"met/parsed",sep="/")
io$acc.indir <- paste(io$basedir,"acc/parsed",sep="/")
io$diffmet.dir <- "/Users/ricard/data/gastrulation_norsync_stuff/met/test/diff_featurelevel"
io$diffacc.dir <- "/Users/ricard/data/gastrulation_norsync_stuff/acc/test/diff_featurelevel"

# Define options
opts <- list()

# Define annotations
opts$annos <-c(
  "H3K27ac_distal_E7.5_Ect_intersect12"="Ectoderm enhancers"
  # "H3K27ac_distal_E7.5_Mes_intersect12"="Mesoderm enhancers",
  # "H3K27ac_distal_E7.5_End_intersect12"="Endoderm enhancers",
  # "K27ac_ESC_distal"="ESC enhancers"
)


# Define which cells to use
sample_metadata1 <- fread(io$in.sample_metadata,stringsAsFactors=T) %>% 
  .[stage%in%c("ICM","ESC","Morula","TE","Zygote","2-cell")]
opts$met.cells <- as.character(sample_metadata1$id_met)
opts$acc.cells <- as.character(sample_metadata1$id_acc)
```

```{r}
io$in.sample_metadata <- "/Users/ricard/data/gastrulation/sample_metadata_scNMT.txt"

opts$stage_lineage <- c(
  "E4.5_EPI",#"E4.5_PE",
  "E5.5_EPI",#"E5.5_PE",
  "E6.5_EPI",# "E6.5_VE","E6.5_PS"
  "E7.5_Ectoderm"#,"E7.5_Mesoderm","E7.5_Endoderm"
)

sample_metadata2 <- fread(io$in.sample_metadata,stringsAsFactors=T) %>% 
  .[,stage_lineage:=as.factor(paste(stage,lineage,sep="_"))] %>%
  .[stage_lineage%in%opts$stage_lineage]
```

```{r}
sample_metadata <- rbind(
  sample_metadata1[,c("id_acc","sample","stage")],
  sample_metadata2[,c("id_acc","sample","stage_lineage")] %>% setnames(c("stage_lineage"),c("stage"))
  )
```

<!-- Load genomic annotations -->
```{r load_annotations, echo=FALSE, warning=FALSE}
anno_df <- lapply(names(opts$annos), function(i) 
  fread(sprintf("%s/%s.bed",io$features.indir,i), stringsAsFactors=T)[,c(1,2,3,4,5,6)]) %>%
  rbindlist %>% setnames(c("chr","start","end","strand","id","anno"))
```

```{r}
# Ectoderm-specific
diff.met.ect <- fread(sprintf("zcat < %s/E7.5Ect_vs_E7.5MesEnd_H3K27ac_distal_E7.5_Ect_intersect12.txt.gz",io$diffmet.dir))

# Mesoderm-specific
diff.met.mes <- fread(sprintf("zcat < %s/E7.5Mes_vs_E7.5EctEnd_H3K27ac_distal_E7.5_Mes_intersect12.txt.gz",io$diffmet.dir))

# Endoderm-specific
diff.met.end <- fread(sprintf("zcat < %s/E7.5End_vs_E7.5EctMes_H3K27ac_distal_E7.5_End_intersect12.txt.gz",io$diffmet.dir))

diff.met <- do.call("rbind", list(diff.met.ect, diff.met.mes, diff.met.end)) %>% 
  .[,sig:=padj_fdr<0.1 & abs(diff)>0.10] %>%
  .[sig==T]
```

```{r}
diff.met[,.N,by="anno"]
```

```{r}
# Ectoderm-specific
diff.acc.ect <- fread(sprintf("zcat < %s/E7.5Ect_vs_E7.5MesEnd_H3K27ac_distal_E7.5_Ect_intersect12.txt.gz",io$diffacc.dir))

# Mesoderm-specific
diff.acc.mes <- fread(sprintf("zcat < %s/E7.5Mes_vs_E7.5EctEnd_H3K27ac_distal_E7.5_Mes_intersect12.txt.gz",io$diffacc.dir))

# Endoderm-specific
diff.acc.end <- fread(sprintf("zcat < %s/E7.5End_vs_E7.5EctMes_H3K27ac_distal_E7.5_End_intersect12.txt.gz",io$diffacc.dir))

diff.acc <- do.call("rbind", list(diff.acc.ect, diff.acc.mes, diff.acc.end)) %>% 
  .[,sig:=padj_fdr<0.1 & abs(diff)>0.10] %>%
  .[sig==T]
```

```{r}
diff.acc[,.N,by="anno"]
```

<!-- Subset differential hits from the data -->
```{r}
# Methylation
anno_df.met.subset <- anno_df %>% split(.$anno) %>%
  map2(.,names(.), function(x,y) x[id %in% diff.met[anno==y,id]] ) %>%
  rbindlist
# anno_df.met.nonsubset <- anno_df[!anno%in%opts$subset.annnos]
# anno_df.met <- rbind(anno_df.met.subset,anno_df.met.nonsubset) %>% droplevels() %>% setkey(chr,start,end)
anno_df.met <- anno_df.met.subset %>% droplevels %>% setkey(chr,start,end)

# Accessibility
anno_df.acc.subset <- anno_df %>% split(.$anno) %>%
  map2(.,names(.), function(x,y) x[id %in% diff.acc[anno==y,id]] ) %>%
  rbindlist
# anno_df.acc.nonsubset <- anno_df[!anno%in%opts$subset.annnos]
# anno_df.acc <- rbind(anno_df.acc.subset,anno_df.acc.nonsubset) %>% droplevels() %>% setkey(chr,start,end)
anno_df.acc <- anno_df.acc.subset %>% droplevels() %>% setkey(chr,start,end)
```

<!-- Load methylation data -->
```{r load_data, echo=FALSE}
# met_dt <- lapply(names(opts$annos), function(n)
#     fread(sprintf("zcat < %s/%s.tsv.gz",io$met.indir,n), stringsAsFactors=T)
#     ) %>% rbindlist
# colnames(met_dt) <- c("id_met","id","anno","Nmet","N","rate")
```

<!-- Load accessibility data -->
```{r}
acc_dt1 <- lapply(names(opts$annos), function(n)
    fread(sprintf("zcat < %s/%s.tsv.gz",io$acc.indir,n), stringsAsFactors=T)
    ) %>% rbindlist
colnames(acc_dt1) <- c("id_acc","id","anno","Nacc","N","rate")
```

```{r}
io$acc.indir <- "/Users/ricard/data/gastrulation/acc/parsed"
acc_dt2 <- lapply(names(opts$annos), function(n)
    fread(sprintf("zcat < %s/%s.tsv.gz",io$acc.indir,n), stringsAsFactors=T)
    ) %>% rbindlist
colnames(acc_dt2) <- c("id_acc","id","anno","Nacc","N","rate")
```

```{r}
acc_dt1 <- acc_dt1[id %in% anno_df.acc$id]
acc_dt2 <- acc_dt2[id %in% anno_df.acc$id]
```

```{r}
# acc_dt <- rbind(acc_dt1,acc_dt2)
acc_dt <- acc_dt2
```


<!-- Merge data with sample metadata -->
```{r}
acc_dt <- acc_dt %>% merge(sample_metadata, by="id_acc") %>% droplevels()
```


```{r}
opts$min.weight <- 3
acc_dt <- acc_dt[N>=opts$min.weight]

# Filter features by  minimum number of cells (by stage_lineage)
opts$min.coverage <- 0.4
nsamples <- length(unique(acc_dt$sample))
acc_dt <- acc_dt[,cov:=.N/nsamples,by=c("id","anno")] %>% .[cov>=opts$min.coverage] %>% .[,c("cov"):=NULL]

# Filter features by variance
acc_dt <- acc_dt[,var:=var(rate),by=c("id","anno")] %>% .[var>0.5] %>% .[,var:=NULL]
```

```{r}
```

```{r}
tmp <- acc_dt[,.(rate=sum(Nacc)/sum(N)),by=c("id","stage")] %>%
  dcast(stage~id, value.var="rate") %>% matrix.please

# tmp <- acc_dt %>%
#   dcast(sample~id, value.var="rate") %>% matrix.please
# dim(tmp)

# foo <- sample_metadata %>% setkey(sample) %>% .[rownames(tmp)] %>% .[,c("sample","stage")] %>% as.data.frame %>% tibble::column_to_rownames("sample")
pheatmap::pheatmap(tmp, show_rownames=T, show_colnames=F, cluster_rows=T)
```
