---
title: "Guo2017_preimplantation: quantification of DNA accessibility in mithocondrial DNA"
output: 
  BiocStyle::html_document: 
    fig_width: 10
    fig_height: 8
---

```{r load_modules, include=FALSE, echo=FALSE}
library(data.table)
library(purrr)
library(ggplot2)
library(ggpubr)
```

```{r define_opts, echo=FALSE, include=FALSE}

## I/O ##
io <- list()

io$metadata <- "/Users/ricard/data/Guo2017_preimplantation/sample_metadata.txt"
io$data <- "/Users/ricard/data/Guo2017_preimplantation/acc/gpc_level"
io$outdir <- "/Users/ricard/Guo2017_preimplantation/out"


## Options ##
opts <- list()

# Define which cells to use
opts$cells <- fread(io$metadata) %>% 
  .[!is.na(id_acc),id_acc]
```

<!-- Load metadata -->

```{r load_metadata}
metadata <- fread(io$metadata) %>% 
  .[id_acc%in%opts$cells]
```

<!-- Load accessibility data -->

```{r}
dt <- list()
for (i in opts$cells) {
  if (file.exists(sprintf("%s/%s.tsv.gz",io$data,i))) {
    dt[[i]] <- fread(sprintf("%s/%s.tsv.gz",io$data,i), sep="\t", verbose=F, showProgress=F) %>% 
      setnames(c("chr","pos","rate")) %>% .[chr=="M"] %>%
      .[,id_acc:=as.factor(i)]
  } else {
    print(sprintf("Sample %s not found",i))
  }
}

dt <- rbindlist(dt) %>% .[,chr:=as.factor(chr)]
```

<!-- Bar plots of average MT accessibility rate per cell -->

```{r}
tmp <- dt[,.(coverage=.N),by="id_acc"]
```

```{r}
# Filter cells by coverage
dt <- dt[,coverage:=.N,by="id_acc"] %>% .[coverage>100]
```

```{r}
to.plot <- dt[,.(rate=mean(rate)), by="id_acc"] %>%
  merge(metadata,by="id_acc")

p <- ggbarplot(to.plot, x="id_acc", y="rate", size=0.25, fill="#00BFC4", 
               facet="stage", scales="free_x") +
  labs(x="", y="chr. accessibility rate in MT") +
  coord_cartesian(ylim=c(0,1)) +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  )
print(p)

# pdf(file=paste0(io$outdir,"/qc_met.pdf"), width=8, height=5)
# print(p)
# dev.off()
```

<!-- Correlate global accessibility rate vs MT accessibility rate -->

```{r}
# stats <- fread("/Users/ricard/data/Guo2017_preimplantation/acc/stats/stats.txt") %>%
#   .[,mean:=mean/100]
# 
# to.plot <- dt[,.(rate=mean(rate)), by="id_acc"] %>%
#   merge(metadata,by="id_acc") %>%
#   merge(stats,by="id_acc")
# 
# p <- ggscatter(to.plot, x="mean", y="rate", facet="stage", color="#00BFC4", add="reg.line", scales="free") +
#   labs(x="Mean accessibility rate", y="MT accessibility rate") +
#   theme(
#     # axis.text.x = element_blank(),
#     # axis.ticks.x = element_blank()
#   )
# print(p)
```

